#!/usr/bin/env bash

GITHUB_USER_PROJECT="$(git config remote.origin.url|cut -d: -f2|cut -d. -f1)"
UPSTREAM=$(git-upstream-ref)
HASH=${1:-HEAD}
PULL=$(git-trace-pull-request $HASH)


echo -n '{quote}'

git log -1 "$HASH" --name-status --date=rfc --pretty=format:"
[Pull request #$(echo $PULL|cut -d/ -f7)|$PULL]
[%h|https://github.com/${GITHUB_USER_PROJECT}/commit/%H]
%an <%ae>
%cr (%ad)

%B"

echo '{quote}'
