#!/bin/bash

# Comments
# - Customize for your installation, for instance you might want to add default parameters like the following:
# java -jar release/jira-cli-1.5.0.jar --server http://my-server --user automation --password automation "$@"

JAR="$HOME/local/lib/jira-cli-2-1.2.0/lib/jira-cli-2.2.0.jar"

if [[ ! -f $JAR ]]; then
    echo "Could not find the jira-cli jar in $JAR" 1>&2
    echo "    Download from https://bitbucket.org/bob_swift/jira-cli/downloads" 1>&2
    echo "    Install to $HOME/local/lib/" 1>&2
    exit 1
fi

SERVER="$(git config jira.server)"

if [[ $SERVER == "" ]]; then
    cat <<-EOF
    How to setup your git repo's Jira config without leaking your password all over the place.

        cd ~/Projects/MyProjectOfDoom
        git config jira.server https://whatever.jira.com/ # Use your actual url
        git config jira.user $USER                        # Use your actual Jira username
        git config jira.password PLACEHOLDER              # Do NOT use your actual password yet
        chmod 600 .git/config
        $EDITOR .git/config

    Now replace PLACEHOLDER with your actual password.
EOF
    exit 1
fi

java -jar "$JAR" --server "$SERVER" --user "$(git config jira.user)" --password "$(git config jira.password)" $@
